### Nomial OHE Encoding

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# create a simple dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [11]:
# create on instance of OneHotEncoder
encoder = OneHotEncoder()

In [12]:
# perform fit & transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [13]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [14]:
encoder.transform([['blue']]).toarray()

c:\udemy\python\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [15]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

### Label Encoding

In [21]:
from sklearn.preprocessing import LabelEncoder

In [23]:
lbl_encoder = LabelEncoder()

In [25]:
lbl_encoded = lbl_encoder.fit_transform(df[['color']])
lbl_encoded

c:\udemy\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [27]:
print(lbl_encoder.transform([['red']]))
print(lbl_encoder.transform([['blue']]))
print(lbl_encoder.transform([['green']]))

[2]
[0]
[1]

c:\udemy\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\udemy\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\udemy\python\venv\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

### Ordinal Encoding

In [28]:
import pandas as pd

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
# create dataset for orinal encoding
df = pd.DataFrame({
    'size' : ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [33]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [36]:
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [37]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [38]:
encoder.transform([['small']])

c:\udemy\python\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

### Target gided ordinal encode

In [39]:
import pandas as pd

In [44]:
# create simple dataframe with categorical variable & target variable
df = pd.DataFrame({
    'city': ['NewYork','London', 'Paris','Tokyo','NewYork','Paris'],
    'price': [200,150,300,250,100,320]
})

In [45]:
df

      city  price
0  NewYork    200
1   London    150
2    Paris    300
3    Tokyo    250
4  NewYork    100
5    Paris    320

In [46]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [47]:
mean_price

{'London': 150.0, 'NewYork': 150.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [48]:
df['city_encoded'] = df['city'].map(mean_price)
df[['price', 'city_encoded']]

   price  city_encoded
0    200         150.0
1    150         150.0
2    300         310.0
3    250         250.0
4    100         150.0
5    320         310.0

#### Example on tips data

In [49]:
import seaborn as sns

In [55]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [56]:
import pandas as pd

In [58]:
mean_bills = df.groupby('day')['total_bill'].mean().to_dict()

C:\Users\abc\AppData\Local\Temp\ipykernel_9496\2511785588.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bills = df.groupby('day')['total_bill'].mean().to_dict()

In [59]:
mean_bills

{'Thur': 17.682741935483868,
 'Fri': 17.15157894736842,
 'Sat': 20.44137931034483,
 'Sun': 21.41}

In [60]:
df['days_encoded'] = df['day'].map(mean_bills)
df[['total_bill', 'days_encoded']]

     total_bill days_encoded
0         16.99    21.410000
1         10.34    21.410000
2         21.01    21.410000
3         23.68    21.410000
4         24.59    21.410000
..          ...          ...
239       29.03    20.441379
240       27.18    20.441379
241       22.67    20.441379
242       17.82    20.441379
243       18.78    17.682742

[244 rows x 2 columns]